### ISSUE TITLE
challenge should not be generated if no any valid validator 

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1285]
It is impossible to pass challenge if there is no any valid validator.  so challenge should not be generated if there is no any available validator.
<img width="2074" alt="Screen Shot 2022-05-19 at 10 10 51" src="https://user-images.githubusercontent.com/347651/169188856-cfd3f13b-9764-401c-b3a1-10a1282c0c99.png">

**Comment by peterlimg** [comment]
@sum-it08 have we fixed this?

**Comment by cnlangzi** [comment]
> @sum-it08 have we fixed this?

I remember I reported the same issue a few months ago. but it still happens on last testing.

**Comment by ssardana08** [comment]
@cnlangzi doesn't look like an issue.
Challenges on 0chain are getting generated perfectly with valid validators.
There might be an issue on blobbers unmarshalling. Please check
Please find attached screenshot from 0chain eventsdb:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/103603196/174653666-5d9a8a07-21ac-451c-aaaf-fbf205fb6775.png">

Closing the issue as it's not valid.
please re-open if faced again.
